### ISSUE TITLE
autogen报错

### ISSUE THREAD

**Issue by lenhoo** [gongjianhui/AppleDNS#12]
Traceback (most recent call last):
  File "autogen.py", line 88, in <module>
    process_file(args)
  File "autogen.py", line 68, in process_file
    output_all(hosts, domains, args.format)
  File "autogen.py", line 54, in output_all
    print '%s = %s' % (domain, hosts[0])
IndexError: list index out of range

**Comment by gongjianhui** [comment]
请查看最新版脚本，修复了问题。（新版需要 Python3 下运行）
