### ISSUE TITLE
Python 有啥要求么？刚刚安装 Py 3.5.1 运行出错。。。

### ISSUE THREAD

**Issue by laincat** [gongjianhui/AppleDNS#15]
```
λ python fetch-timeout.py --payload ChinaNet.json
Traceback (most recent call last):
  File "fetch-timeout.py", line 104, in <module>
    main()
  File "fetch-timeout.py", line 99, in main
    payload = fetch(json.load(open(args.payload)))
  File "D:\Program Files\Python\lib\json\__init__.py", line 265, in load
    return loads(fp.read(),
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa2 in position 5467: illegal multibyte sequence
```
=. = 不明白啥问题。。。(小白一枚)

**Comment by gongjianhui** [comment]
检查几个文件的编码。

**Comment by gongjianhui** [comment]
是 Windows 的文件编码问题，证在试图修复。

**Comment by laincat** [comment]
感激（期待。。。）

**Comment by gongjianhui** [comment]
已修复，请重新下载尝试。

**Comment by gongjianhui** [comment]
如果问题修复，请反馈。

**Comment by laincat** [comment]
不明白为什么，还是一样的错误。

**Comment by gongjianhui** [comment]
请再次测试（抱歉

**Comment by laincat** [comment]
可以了！大感谢！
