### ISSUE TITLE
Music.json 报错

### ISSUE THREAD

**Issue by EricDiao** [gongjianhui/AppleDNS#16]
错误信息如下：
`ericdiao@ericdiao-ThinkPad:~/appledns/AppleDNS$ python3 fetch-timeout.py --payload Music.json
Traceback (most recent call last):
  File "fetch-timeout.py", line 105, in <module>
    main()
  File "fetch-timeout.py", line 100, in main
    payload = fetch(json.load(open(args.payload)))
  File "/usr/lib/python3.4/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)`

**Comment by gongjianhui** [comment]
新版已修复，把 JSON 里面的注释删掉。

**Comment by gongjianhui** [comment]
解决了吗？

**Comment by EricDiao** [comment]
解决。
