### ISSUE TITLE
Ubuntu 64位hosts报错

### ISSUE THREAD

**Issue by Babesun** [gongjianhui/AppleDNS#21]
ubuntu:~/AppleDNS$ python3 export-configure.py --target hosts
Traceback (most recent call last):
  File "export-configure.py", line 52, in <module>
    main()
  File "export-configure.py", line 48, in main
    export(payload, args.target)
  File "export-configure.py", line 28, in export
    fast_ip = find_fast_ip(service['ips'])
  File "export-configure.py", line 22, in find_fast_ip
    ip, rt = sorted(table, key=lambda item: item[1])[0]
IndexError: list index out of range

**Comment by gongjianhui** [comment]
你确定运行了 fetch-timeout.py? (运行了文件夹中应该有一个 result.json )

**Comment by septs** [comment]
请按照README操作
