### ISSUE TITLE
export-configure hosts error

### ISSUE THREAD

**Issue by decimalbell** [gongjianhui/AppleDNS#29]
```bash
./export-configure.py hosts
Traceback (most recent call last):
  File "./export-configure.py", line 79, in <module>
    main()
  File "./export-configure.py", line 75, in main
    export(load_payload(), args.target)
  File "./export-configure.py", line 45, in export
    fast_ip = find_fast_ip(service['ips'])
  File "./export-configure.py", line 36, in find_fast_ip
    if len(table):
TypeError: object of type 'map' has no len()

**Comment by septs** [comment]
fix
